#!/bin/sh
. "$(dirname $0)/env"
username=$(docker info | sed '/Username:/!d;s/.* //')
if test -z $username
then
    echo docker login first
    exit 2
fi
version=$($script_dir/oversion)
test ! -z "$(docker images -q owt-base)" || docker build -t "owt-base" "$base_dir"
docker_push()
{
    docker tag "owt-base" "$username/owt-base:$1"
    docker push "$username/owt-base:$1"
}
for i in $*
do
    docker_push $i
done
docker_push $version
docker_push latest
